export { default as Header } from "./Header"
export { default as Footer } from "./Footer"
export { default as Proyectos } from "./Proyectos"
export { default as Experiencia } from "./Experiencia"
export { default as Conocimiento } from "./Conocimiento"